# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.BooleanField(default=False)),
                ('location', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('interviewer', models.CharField(max_length=50)),
                ('observer', models.CharField(max_length=50)),
                ('videourl', models.URLField()),
                ('hist_img', models.ImageField(upload_to=b'')),
                ('curr_img', models.ImageField(upload_to=b'')),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('time_posted', models.DateTimeField(null=True)),
                ('hist_year', models.DateField()),
                ('curr_year', models.DateField()),
                ('hist_caption', models.CharField(max_length=200)),
                ('curr_caption', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('key_words', models.TextField()),
                ('contact_org', models.URLField()),
                ('steward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
