# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtalkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='curr_img',
            field=models.ImageField(null=True, upload_to='landtalk/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hist_img',
            field=models.ImageField(null=True, upload_to='landtalk/'),
        ),
    ]
