# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtalkapp', '0004_auto_20170303_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='privkey',
            field=models.IntegerField(default=-1, verbose_name='PK'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='curr_img',
            field=models.ImageField(upload_to='landtalk/f2303a8c1b36468ba92238c1cd34feec.curr', verbose_name='Current Image'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hist_img',
            field=models.ImageField(upload_to='landtalk/f0fdc851392c4b8b832314a02ab3925c.hist', verbose_name='History Image'),
        ),
    ]
