# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtalkapp', '0005_auto_20170309_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='privkey',
        ),
        migrations.AlterField(
            model_name='submission',
            name='curr_img',
            field=models.ImageField(upload_to='landtalk/322a3007fabe46ebb54d8af78d7ee4ee.curr', verbose_name='Current Image'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hist_img',
            field=models.ImageField(upload_to='landtalk/ea081ef37025475dbf498bd35f28f71b.hist', verbose_name='History Image'),
        ),
    ]
